---
- name: Смена пароля пользователя на MikroTik
  hosts: routers
  gather_facts: false

  vars:
    TARGET_USER: "{{ user_change_password }}"
    NEW_PASS: "{{ ansible_user_password }}"

  tasks:
    - name: "Проверка переменной user_change_password"
      ansible.builtin.fail:
        msg: "❌ Укажите user_change_password в .env или через -e"
      when: TARGET_USER == "" or TARGET_USER is not defined

    - name: "Смена пароля для {{ TARGET_USER }}"
      ansible.builtin.shell:
        cmd: |
          sshpass -p "{{ mikrotik_password }}" \
          ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          {{ mikrotik_user }}@{{ ansible_host }} \
          "/user set [find name={{ TARGET_USER }}] password={{ NEW_PASS }} group=full"
      delegate_to: localhost
      register: change_result
      no_log: true

    - name: "Список всех пользователей"
      ansible.builtin.shell:
        cmd: |
          sshpass -p "{{ mikrotik_password }}" \
          ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          {{ mikrotik_user }}@{{ ansible_host }} \
          "/user print"
      delegate_to: localhost
      register: all_users

    - name: "Результат"
      ansible.builtin.debug:
        msg: |
          ✅ {{ ansible_host }}: пароль для {{ TARGET_USER }} изменен

          📋 СПИСОК ВСЕХ ПОЛЬЗОВАТЕЛЕЙ:
          {{ all_users.stdout }}
